### ISSUE TITLE
Does not add lazy="loading" on my jekyll site

### ISSUE THREAD

**Issue by solrevdev** [gildesmarais/jekyll-loading-lazy#6]
**Expected output** 

```html
<p><img src="https://i.imgur.com/1MyvTwn.png" alt="" lazy="loading" /></p>
```

**Actual output** 

```html
<p><img src="https://i.imgur.com/1MyvTwn.png" alt="" /></p>
```

All source code is here : [https://github.com/solrevdev/solrevdev.github.io](https://github.com/solrevdev/solrevdev.github.io)

I am sure it's just me doing something wrong. I do not use Jekyll and Ruby elsewhere so not in my wheelhouse!

**Gemfile**

```ruby
source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll'
gem 'jekyll-redirect-from'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'html-proofer'
gem 'rake'
gem 'jekyll-github-metadata'
gem 'jemoji'
gem 'jekyll-seo-tag'
gem 'jekyll-loading-lazy'
```

**_config.yml**

```yml
# Plugins
plugins:
    - github-pages
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-github-metadata
    - jemoji
    - jekyll-seo-tag
    - jekyll-loading-lazy

# Dependencies
highlighter: rouge
markdown: kramdown

# Permalinks
# excerpt_separator: ''

# Setup
title: "solrevdev"
tagline: "developer / devops / comedy nerd / full time carer"
description: "A blog about things I find on the web, tools and technologies that I like."
url: "https://solrevdev.com"
baseurl: ""

# Contacts
author:
    name: "John Smith"
    url: "https://solrevdev.com/about/"
    email: "john@solrevdev.com"
    github: "https://github.com/solrevdev"
    facebook: "https://www.facebook.com/solrevdevtechradar"
    instagram: "https://www.instagram.com/solrevdev"
    twitter: "https://www.twitter.com/solrevdev"

# Outputting
paginate: 5

# Custom vars
version: "2.1.0"

github: [metadata]

exclude: ["Rakefile", "vendor"]

# Social Sharing
facebook_app_id: "123456789"

theme: jekyll-theme-cayman

prose:
    siteurl: "https://solrevdev.com"
    media: "media"
```
**Output**

```shell
bundle exec jekyll serve --drafts 2>/dev/null
Configuration file: /home/solrevdev/Code/github/solrevdev.github.io/_config.yml
            Source: /home/solrevdev/Code/github/solrevdev.github.io
       Destination: /home/solrevdev/Code/github/solrevdev.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 11.697 seconds.
 Auto-regeneration: enabled for '/home/solrevdev/Code/github/solrevdev.github.io'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```
